### ISSUE TITLE
Code?

### ISSUE THREAD

**Issue by fmaussion** [mankoff/ice_discharge#18]
Hi @mankoff ! Congrats on the great work, I think it will be very useful to the community.

The paper mentions that the code is located here - do you plan to do that? Thanks!

**Comment by fmaussion** [comment]
(also: thanks a congrats for citing the software packages used in the work, this isn't done very often)

**Comment by mankoff** [comment]
You're welcome for the citation. It should be done - I don't see a big distinction between software, data, and other science papers supporting our work/ideas/arguments at the citation level.

The code is published. It is in the [ice_discharge.org](https://github.com/mankoff/ice_discharge/blob/master/ice_discharge.org) file. That is a literate document and everything is contained within it, and I run the code from that file inside Emacs. You don't see the code on GitHub because I have set the `:exports` flag to either `none` or `results`, but if you view the raw Org file you will see the code.

I've considered tangling the code out of the file and including Python and Bash source files in the git repository, but I don't edit or run those files, so I have not yet done that. I recognize this increases the work for others to use and replicate this project, but so far you are the first to request the code...

**Comment by mankoff** [comment]
Also, based  on your research and thumbnail graphic you may be interested in https://github.com/mankoff/freshwater/ and the associated paper at https://www.earth-syst-sci-data-discuss.net/essd-2020-47/

**Comment by fmaussion** [comment]
> That is a literate document and everything is contained within it, and I run the code from that file inside Emacs.

Ha! I've never heard of such a workflow - quite interesting! Some kind of emacs style jupyter notebook I guess? :thinking: 

Not the best for readability outside of the emacs framework from my non-emacs perspective, but if it works for you that's great! Thanks for sharing.

**Comment by mankoff** [comment]
Yes, just a notebook, sort-of like Jupyter, but Emacs-centric. See Org-Mode and Babel also cited in the paper. In some senses less readable than Jupyter notebooks, but on the other hand this is ASCII plain text so anyone can view it, no web-server and JSON parser required. You can't easily **run it** outside of Emacs, but lots of editors have Org syntax support to let you read it with syntax highlighting.

But as I said you're the first to show interest. I'd like it to be useful for others so if this appears to be an issue I can export the code. If you're *really interested* in the code, not just checking that it was released, I can send you something...

**Comment by fmaussion** [comment]
I was interested in some parts as interested for some future work I'd like to do with OGGM - but no need to make efforts and change your workflow because of me. I'll find my way in the org file!

**Comment by mankoff** [comment]
OK - I'll leave it for now, but please reach out if you want to collaborate or have any questions.

**Comment by fmaussion** [comment]
> I was interested in some parts for some future work I'd like to do with OGGM

Actually: I changed my mind: can YOU do it instead? ;-)

Joke aside: there is ice velocity available for many glaciers now (its-live-data.jpl.nasa.gov).

I have a suite of tools which can provide you a [map of ice thickness](https://www.nature.com/articles/s41561-019-0300-3), [ice velocities re-projected to it](https://github.com/OGGM/oggm/blob/master/oggm/shop/its_live.py), and [topography](https://rgitools.readthedocs.io/en/latest/dems.html) for almost all glaciers where calving is relevant.

The uncertainties will be MUCH higher, both in the ice thickness and in the velocities (and there is a little bit of [chicken and egg problem with the ice thickness of calving glaciers](https://www.the-cryosphere.net/13/2657/2019/)) but the estimates you provide for Greenland would be of extreme value for the glacier community as well. We wanted to do something similar as you did, but it would be much better if you do it instead!

**Comment by mankoff** [comment]
Do *what* exactly?

The URL you shared doesn't seem to work but I'm familiar with ITS-LIVE. I *think* it is mostly a re-package of MEaSUREs data set, which is used heavily in this (ice_discharge) work.

I saw your paper when it came out last year - congratulations on that! - and re-found it a few months ago. I was wondering if it could be used to improve our thickness estimates. As discussed in my paper there are many places where BedMachine reports 1 or 10 m thickness but velocities are > 100 m/yr. My fix is fairly simple. I was going to reach out to your team at some point to see if you could improve the thickness fix that I'm using.

But I'm still not clear what you're asking me to do... estimate flux for all mountain glaciers worldwide? Or just export my code and share that so you can see my methods more clearly?

**Comment by fmaussion** [comment]
> estimate flux for all mountain glaciers worldwide?

Yes - you have the expertise and the tools, I can provide some data (although everything is freely available, we just spent some time to have it processed and nicely organized). It would be quite some work but of very high relevance for the RGI community.

I you have some bandwidth available I'd be happy to chat. you'll find my email on my website: https://fabienmaussion.info/
